Resources:
 myDynamoDBTable:
  Type: AWS::DynamoDB::Table
  Properties:
   AttributeDefinitions:
     - 
          AttributeName: "shortCode"
          AttributeType: "N"
   ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
   KeySchema: 
    - 
     AttributeName: "shortCode"
     KeyType: "HASH"
   TableName: "URL"
 maxIdTable:
  Type: AWS::DynamoDB::Table
  Properties:
   AttributeDefinitions:
     - 
      AttributeName: "id"
      AttributeType: "N"
   ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
   KeySchema: 
    - 
      AttributeName: "id"
      KeyType: "HASH"
   TableName: "maxId"